#!/bin/sh

cd "$1"

PATCH_GO_VERSION=$(egrep '^go ' go.mod | awk '{print $2}' | sed -e 's+^\([0-9]*\.[0-9]*\)[^0-9]*.*$+\1+')
PATCH_GO_PATH="$(ls -d ${RUNNER_TOOL_CACHE}/go/${PATCH_GO_VERSION}.*/*/bin)"
export PATH="${PATH}:${PATCH_GO_PATH}"

echo "Patching go dependencies to address vulnerabilities"

go get \
   github.com/cilium/cilium@1.16.4

echo "Running go mod tidy"
go mod tidy

echo "Running clean of the modcache"
go clean -modcache
